### ISSUE TITLE
Ability to setup local instance with docker

### ISSUE THREAD

**Issue by indrif** [Etimo/diamonds#16]
The docker script seems to be working for etimo-app-server only.

**Comment by EtimoOscarNylander** [comment]
It should be fine even when not running on etimo-app-server.

    ./deploy.sh

is only if you want to specifically deploy to etimo-app-server, the way to bring it up locally is to use:

    docker-compose up

We can take a look at it tomorrow :)

**Comment by EtimoOscarNylander** [comment]
I added a basic readme, should cover the essentials.

**Comment by jens-peterolsson** [comment]
We should also have debugging etc. when running from VS code working for both front-end and back-end. So either this issue could cover that or we should create another one for it.

**Comment by indrif** [comment]
We should also fix config for docker vs localhost when it comes to mongodb connection string
