### ISSUE TITLE
Onboarding information

### ISSUE THREAD

**Issue by indrif** [Etimo/diamonds#29]
Some kind of information (perhaps link to github readme) regarding how to get started and where to find implementation information. A link in the game gui?

**Comment by indrif** [comment]
Include branding

**Comment by indrif** [comment]
Link to api

**Comment by jens-peterolsson** [comment]
Create Docker.md and move current content from Readme.md
New ReadMe.md with link to swagger api spec (/api/docs) + link to example bots + describe limits etc.
Update link in GUI to github root (How to play)
Remove text file api spec
Review folder and MD-structure

**Comment by joakim-olesen** [comment]
I reopen the issue since we found out the documentation is incorrect/incomplete for to `Get board by id`and `Get bot by id`

**Comment by joakim-olesen** [comment]
I believe this can now be closed (again). @indrif: I updated bullet 3 at https://github.com/etimo/diamonds If it's still not correct, just reopen this ticket.
