### ISSUE TITLE
Register bot issue

### ISSUE THREAD

**Issue by SockeTopp** [Etimo/diamonds#57]
I cloned the repo and tried to register a bot with the following command:
$ python main.py --name myName--email myLiuId@student.liu.se --logic Random

First issue was the import of random in crash_in_the_middle.py which should be: from random import random. This was an easy fix. 

However, second time around I received this error message: 

` File "C:\Python27\lib\site-packages\requests\adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/bots (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000060B2A20>: Failed to establish a new connection: [Errno 10061] Det gick inte att g\xf6ra en anslutning eftersom m\xe5ldatorn aktivt nekade det',))`

The issue points to
`result = bot.register()`
In main.py
Which refers to
`req = func(self._get_url(endpoint), headers=headers, data=json.dumps(body))`
in api.py

I suspect that the server is down for the moment perhaps?

**Comment by teozkr** [comment]
Looks like the problem is that the default host is http://localhost:81/api (see https://github.com/Etimo/diamonds/blob/4aae45383bfd7dc43371e993c7f3e74162457114/diamonds-bot-example/main.py#L17).
