### ISSUE TITLE
Button on board that regenerates diamonds

### ISSUE THREAD

**Issue by indrif** [Etimo/diamonds#59]
Simply put a button/game object on the board that, when stepped on, regenerates all diamonds on the board.

**Comment by teozkr** [comment]
Fixed by @sirscratchalot in https://github.com/Etimo/diamonds/commit/c6091012a9af1600967c484e86e0c191837d1a84.

**Comment by indrif** [comment]
Apparently it regenerates bases as well which maybe is not the desired outcome. Reopened.

**Comment by sirscratchalot** [comment]
Adjusted, now button moves to random position and diamonds are regenerated.
