### ISSUE TITLE
Teleports and diamond button can spawn on the same cell

### ISSUE THREAD

**Issue by indrif** [Etimo/diamonds#70]
<img width="1154" alt="skarmavbild 2019-02-26 kl 19 38 38" src="https://user-images.githubusercontent.com/6198331/53437677-645fff00-39fe-11e9-8685-832653733ff9.png">

**Comment by sirscratchalot** [comment]
Both teleports and diamonds use the getRandomEmptyPosition (or similiar) method to get a position, should double check behaviour of that method.

**Comment by sirscratchalot** [comment]
Ok, for some reason reading Diamond Button is beyond me and I kept reading "Diamond" and "Teleporter".
Since "Diamond Button" and "Teleport" are two GameObjects this is (very likely) fixed in: 1079542c7292ba13ee772c32424ef527f5ee3858
