### ISSUE TITLE
Allow POST "/boards/{id}/move" to return game state even if move fails

### ISSUE THREAD

**Issue by miniwa** [Etimo/diamonds#80]
Whenever a bot makes a move that fails for some reason (blocked or tries to move out of bounds), code 409 is returned by the server. The response, however, does not contain the state of the game in its body.

This is very painful when latency is 50-60ms and you are allowed to move every 100ms, as you need to wait for an additional request to GET /boards/{id} to complete.

**Comment by ljukas** [comment]
@miniwa How can you mitigate this issue yourself in the mean time? Maybe try running your bot closer to the server?

Not saying this isnt a valid issue, but there are ways around this.

**Comment by miniwa** [comment]
@ljukas 
Yes, reducing the latency makes this issue insignificant.
It's not a terribly complicated fix though, I've made a pull request with a solution.

**Comment by joakim-olesen** [comment]
Thank you @miniwa. I've merged your pull request.
