### ISSUE TITLE
Please consider adding a license

### ISSUE THREAD

**Issue by devLotto** [Etimo/diamonds#82]
Hi! 

I noticed that the project doesn't state that it's licensed under any free license anywhere, which means other people cannot legally copy or modify the software: [No License](https://choosealicense.com/no-permission/)

I don't know if this is intentional or an oversight, and I haven't seen any prior discussion about it, so I'm curious to see how you guys feel about it.

**Comment by teozkr** [comment]
Thanks for raising this. I'm pretty sure this is just due to nobody thinking of it.

I (personally) like the AGPL for "application-scale" projects like this, but I don't have a horse in the race since most of this was developed before my time here.

/cc @indrif @joakim-olesen @JohanHazelius

**Comment by indrif** [comment]
I vote for the most allowing license available.

**Comment by teozkr** [comment]
@indrif I guess that would be the [WTFPL](http://www.wtfpl.net/)? :P

**Comment by indrif** [comment]
YES! Finally a real license! That is exactly what I vote for!

**Comment by teozkr** [comment]
Fixed by https://github.com/Etimo/diamonds/commit/fa105b354de96d5f5d092385008f8bba9ba1462b
